### ISSUE TITLE
Optional client secret

### ISSUE THREAD

**Issue by astralko** [pop-srw/streamlit-cognito-auth#2]
Since AWSSRP do not require client secret and it is only an optional argument,
can you change the client secret to be optional and not a requirement?

**Comment by astralko** [comment]
I added the option in my own fork, here if you like to add it

https://github.com/pop-srw/streamlit-cognito-auth/commit/f7307b6e48c1b5cc00c581f316bb5991dce42528

**Comment by pop-srw** [comment]
Hi, @astralko.

Thanks for reaching out and sharing your thoughts on my work. I'm actually planning to make the client secret optional in the next version. I just haven't had a chance to test it out yet since all my projects currently use the client secret.

I saw that you made a fork with the optional client secret argument. That's awesome! I'll take a look and see if we can add it to our main branch. By the way, do you think we should have an optional client secret for the aws_srp instance in the code you shared?
https://github.com/pop-srw/streamlit-cognito-auth/blob/f7307b6e48c1b5cc00c581f316bb5991dce42528/src/streamlit_cognito_auth/auth.py#L102-L109

Thanks again for your feedback, and feel free to reach out if you have any more ideas or questions.

**Comment by pop-srw** [comment]
I already add support for cognito pools without app client secret. [v.1.2.0](https://github.com/pop-srw/streamlit-cognito-auth/releases/tag/v1.2.0)
